[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "./lib/cairo_erc_3525/src",
    "src",
]

[contracts]
ERC721MetadataUpdate = ["src/migrator/presets/Migrator.cairo"]

[test]
target = ["tests"]

