[package]
name = "migrator"
version = "2.0.3"

[lib]

[dependencies]
starknet = ">=2.2.0"
cairo_erc_3525 = { git = "https://github.com/carbonable-labs/cairo-erc-3525", tag = "2.0.10" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
exit_first = false