[package]
name = "migrator"
version = "2.0.2"

[lib]

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "fcdd6d1b02306f18f1089656f15b87d1701ffde3" }
cairo_erc_3525 = { git = "https://github.com/carbonable-labs/cairo-erc-3525", tag = "2.0.8" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
exit_first = false